### ISSUE TITLE
No save dialog opens with latest Zenity (3.91.0).  (No longer implements "--confirm-overwrite")

### ISSUE THREAD

**Issue by stiberger** [AndrewBelt/osdialog#24]
OpenSuse Tumbleweed now has this version of *Zenity* as default.
When launching file save dialog from *VCVRack*, nothing happens - except a message on the console.
```This option is not available. Please see --help for all possible usages.```

As a workaround I have tried to comment out addition of this command parameter, and this seems to work - though not a permanent solution.
https://github.com/AndrewBelt/osdialog/blob/1c9aaab9aae8df296439d46bd83acbf326522ea7/osdialog_zenity.c#L183

Not sure if this is an upstream issue.

![Screenshot_20230408_034259](https://user-images.githubusercontent.com/6574746/230720293-557635fc-0339-41ae-b036-0cd1277aa6d4.png)
![Screenshot_20230408_034821](https://user-images.githubusercontent.com/6574746/230720297-4c1f1b61-fc2a-4be5-9dc2-f1e6f6bb8354.png)
![Screenshot_20230408_034550](https://user-images.githubusercontent.com/6574746/230720299-9a55cbbf-e450-453e-9f01-ca0b86bc05fe.png)

**Comment by AndrewBelt** [comment]
`--confirm-overwrite` was probably accidentally removed in a merge in https://gitlab.gnome.org/GNOME/zenity/-/commit/f17a8bfc875fada1a79e42f6f07119e91a6955f4. I'll report to the Zenity repo, but unfortunately I'll have to remove `--confirm-overwrite` in osdialog for several years, since Zenity's bug is out in the wild.

Removed flag in e2921e9

**Comment by AndrewBelt** [comment]
Filed bug report at https://gitlab.gnome.org/GNOME/zenity/-/issues/55
Added workaround in 9d46d8bb91e53c2f201333e058d8cbd7916949a6 that checks if `--confirm-overwrite` is available.
